### ISSUE TITLE
Forked

### ISSUE THREAD

**Issue by rochacbruno** [gangverk/flask-swagger#12]
Hi, I forked it here: https://github.com/rochacbruno/flasgger
Added a demo app http://flasgger-rochacbruno.rhcloud.com/

As ai changed many things, included SwaggerUI embedded to the extension, changed from function to class based and blueprint based views.

So I did not sent a pull request yet.

Are you interested in merge? (we can keep backwards compatibility) or simply mention each extension on READMEs.

Thanks for the work!

Open Source Rocks!

**Comment by atlithorn** [comment]
Hi Bruno, thanks for this! I'll definitely have a look and think about this. 

Not a huge fan of embedding SwaggerUI seeing how it's a fast-moving target itself and I don't want flask-swagger to get in people's way with that (it's also one of the reasons I wrote flask-swagger instead of using flask-restful-swagger)
